### PR TITLE
Change version of libssl since the older one got archived

### PR DESCRIPTION
**Pull request by sadatnfs**
Updating link from debian packages

### CODE REVIEW

**Comment by cboettig** [comment]
indeed, thanks @sadatnfs!

Um, would you mind adding this change to the other Dockerfiles in `rstudio` directory as well? (e.g. each of the other subdirectories, 3.3.1 through 3.4.2).  Otherwise I'll get around to it soon enough ;-)

**Comment by cboettig** [comment]
Nice, thanks!

**Comment by sadatnfs** [comment]
Oh, as a heads up, it looks like versions before 3.4.x didn't pull in SSL separately (maybe older Debian versions) and so I didn't update those

**Comment by sadatnfs** [comment]
(Also, I made another commit to remove the DS_Store files which I accidentally added)

**Comment by cboettig** [comment]
Yup, right, images before 3.4 are building on `debian:jessie` instead of `debian:stretch` so they don't need this.  thanks again.

**Pull request merged**
