### PR TITLE
Geospatial base

### PR DESCRIPTION
**Pull request by rkrug**
Sort libraries and options alphabetically and add libraries as suggested by @mdsumner at rocker-org/rocker#213 (comment)

### CODE REVIEW

**Comment by cboettig** [comment]
Thanks, yeah, that's the standard practice in Dockerfiles.  Can you pull from master first to resolve conflicts?

**Comment by rkrug** [comment]
@cboettig Done.

**Comment by cboettig** [comment]
Nice, thanks!

**Comment by rkrug** [comment]
Thanks - was easier than I thought.

**Comment by cboettig** [comment]
@rkrug grr, Docker Hub build failed. missing tiff headers by the look of it?  Can you take a look and fix?

**Comment by rkrug** [comment]
OK - I'm on it.

**Comment by rkrug** [comment]
I am at the moment running the build locally - do you have the error message or is it on travis-ci?

**Comment by cboettig** [comment]
I get the error message from docker hub, but I don't think hub will show you the logs: https://hub.docker.com/r/rocker/geospatial/builds/ (docker hub doesn't have the same granular access permissions of github)

I do have a circle-CI build set up for the other images in the repo here, but it would probably time out if I tried including geospatial image as well.  Guess that's one advantage of putting the dockerfiles in separate repos; guess we could do that.

**Comment by rkrug** [comment]
Still trying - should have it in an hour.

**Pull request merged**
