### PR TITLE
switch libv8-dev to libv8-3.14-dev

### PR DESCRIPTION
**Pull request by noamross**
As described in #28

### CODE REVIEW

**Comment by cboettig** [comment]
Are you sure?  It looks like these are the same thing on verse (recall verse is based on debian:jessie repos):


Here's `libv8-dev` on `verse`: 

```
$ apt-cache show libv8-dev
```


```
Package: libv8-dev
Source: libv8-3.14
Version: 3.14.5.8-8.1
Installed-Size: 307
Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Architecture: amd64
Replaces: libv8-3.14-dev, libv8-legacy-dev
Depends: libv8-3.14.5 (= 3.14.5.8-8.1)
Conflicts: libv8-3.14-dev, libv8-legacy-dev
Description: V8 JavaScript engine - development files for latest branch
Description-md5: e5a031495329bc2268b25d8a571fac58
Homepage: http://code.google.com/p/v8/
Tag: devel::lang:ecmascript, devel::library, devel::runtime,
 implemented-in::c++, role::devel-lib, works-with-format::json
Section: libdevel
Priority: optional
Filename: pool/main/libv/libv8-3.14/libv8-dev_3.14.5.8-8.1_amd64.deb
Size: 108568
MD5sum: 4c9e1ce071b566b9357cc2333bba7aad
SHA1: fb884da549e5439517d2a586f7b47f68d884ac6a
SHA256: adbc235dcb507eb515d64235d9780a7497a5091376f67a416383c212414c0133
```

And here's `libv8-3.14-dev`:

```
$ apt-cache show libv8-3.14-dev
```

```
Package: libv8-3.14-dev
Source: libv8-3.14
Version: 3.14.5.8-8.1
Installed-Size: 307
Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Architecture: amd64
Replaces: libv8-dev
Provides: libv8-dev, libv8-legacy-dev
Depends: libv8-3.14.5 (= 3.14.5.8-8.1)
Conflicts: libv8-dev
Description: V8 JavaScript engine - development files for 3.14 branch
Description-md5: 847e12c681602b10d0e5f037652a8043
Homepage: http://code.google.com/p/v8/
Tag: devel::library, role::devel-lib
Section: libdevel
Priority: optional
Filename: pool/main/libv/libv8-3.14/libv8-3.14-dev_3.14.5.8-8.1_amd64.deb
Size: 108562
MD5sum: 5a4902f53c9415941698598af3c5f323
SHA1: bff1d569766ceb4ece33ee72e724c1f6ab8626cb
SHA256: eba306ef9bd3975d92247eec5112e736f78b0c0ef8b9c67f7169cae3b0d746bf```
```


So default is also 3.14, no? (Though I see the latter is a different file with a different hash, not quite sure what's up with that).  

Can you give an example of what seems broken with the current `libv8-dev`?  So far I haven't had trouble with packages that use v8 (eg `jsonld`)

**Comment by noamross** [comment]
Huh, now I'm failing to install V8 even with this change:

```
> install.packages('V8')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/V8_1.5.tar.gz'
Content type 'application/x-gzip' length 327013 bytes (319 KB)
==================================================
downloaded 319 KB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=-I/usr/include/v8-3.14
Using PKG_LIBS=-lv8
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because  was not found. Try installing:
 * deb: libv8-3.14-dev (formerly: libv8-dev) (Debian, Ubuntu)
 * rpm: v8-314-devel (formerly: v8-devel) (Fedora, EPEL)
 * brew: v8@3.15 (OSX) -- NOT regular v8! Tap from homebrew/versions
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘V8’
* removing ‘/usr/local/lib/R/site-library/V8’
Warning in install.packages :
  installation of package ‘V8’ had non-zero exit status
```

(Running as the RStudio user, in Docker locally)

**Comment by noamross** [comment]
Now I realize that `libv8` may be frozen at 3.14 on Jessie, while on other systems (definitely `brew`), there are more recent versions that don't work.

**Comment by cboettig** [comment]
@noamross Right.  jessie is `debian:stable` for a reason ;-).  

Looks like I never tickled hub builds for verse:latest, 3.3.3, or 3.3.4, so it just hadn't installed libv8-dev yet on those.  Queued 'em up now.  Meanwhile `verse:devel` rebuilds every night automatically and should have the latest

**Comment by noamross** [comment]
Yup, things work just fine on `verse:devel`.  [slinks away]

**Comment by cboettig** [comment]
More precisely, distros like Debian and Ubuntu don't bump the source versions of their packages after actual release, e.g. `debian:8`, which gets a codename (`debian:jessie`), and `debian:stable` always points to the most recent stable release. In contrast, `debian:testing` (which can also be accessed by its codename even before release) and `debian:unstable` (always codenamed `debian:sid`) *do* upgrade these things all the time, so this problem can effect the main `rocker/r_base` images, which build on a mix of `testing` and `unstable`.  

Anyway, glad you got me to tickle the builds.  since I wanted nightly builds for devel but not the other tags I've put all builds on a cron-based update and disabled the build-on-commit or build-when-FROM repo updates.  see: http://www.carlboettiger.info/2017/04/27/new-rocker-releases/ (wait, what! I once again have a blog?!)

**Pull request closed without merging**
