### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by rkrug**

### CODE REVIEW

**Comment by rkrug** [comment]
Here is the working version - at least when I build the docker file. Let's hope the best.

**Comment by cboettig** [comment]
Somehow you still have conflicts with master on this branch. Can you resolve and double check that it still builds?

**Comment by rkrug** [comment]
Fixed them - very strange. Just before I committed, I did the same procedure. Well - now they seem to have gone.

**Comment by rkrug** [comment]
They were only the added libraries and comments.

**Comment by rkrug** [comment]
I am just torturing my computer with a new build.

**Comment by rkrug** [comment]
OK - build successfully. You can merge.

**Comment by cboettig** [comment]
nice, thanks.

**Comment by rkrug** [comment]
Thanks for your patiance.

**Pull request merged**
