### PR TITLE
Add semantic version labels

### LINKED ISSUE #42: Aliases for latest point releases of each version
It might be helpful to have aliases for latest point releases of each version.
So something akin to `3.1.latest`, `3.2.latest`.... `3.4.latest`.

Also `stable` which points to latest 3.x.latest (3.4.1 currently), and `oldrel` which points to latest point release of current -1 release. 

Also 3.2.5 is missing from the builds.

### PR DESCRIPTION
**Pull request by nuest**
Fixes #42

### CODE REVIEW

**Comment by cboettig** [comment]
Thanks @nuest , let's give this a try!  

Do we need to fiddle with anything on Docker Hub (or the cron job triggers) to activate this?

**Comment by nuest** [comment]
Thanks! I forget to suggest a squashed merge... apologies for the messy commits.

_No, nothing else to._

The hooks should run on the next triggered build of the Dockerfiles in the `x.y.z` directories. Since the latest builds are based on separate Dockerfiles, which do not have hooks, and last non-push builds are 16 days old, we have to wait a bit for the tags to appear.

**Comment by cboettig** [comment]
Hey @nuest ,

Looks like, for some reason, the CRON jobs that used to trigger just `latest` and `devel` are now triggering the entire build stack, which we don't want to do.  I think this is due to the `post_hook`s, but maybe not.  

I've added your docker hub user to the `rockerver` team, which has admin access to the hub repos, in case you want to try and troubleshoot.

I can email you my cron table in case it's at fault.

**Comment by cboettig** [comment]
Ok, looks like I was missing some quotations in my `POST` data cron trigger that caused the full builds.  Sorry about that.  (had to recreate the cron job after some server issues and wasn't careful). 
 Trying this again now.  Thanks again for the PR.

**Comment by nuest** [comment]
No worries, saved by being busy. Apologies for not looking into this sooner.
What's your next step: Wait for the CRON jobs to kick in again?

**Comment by cboettig** [comment]
Yups. I've already tickled a bunch of the builds, haven't checked if everything has been finished though.  put check out: `docker pull rocker/r-ver:3` or `docker pull rocker/tidyverse:3.3`

**Pull request merged**
